version: "3.9"

services:
    cloudflared:
        container_name: Cloudflared
        image: cloudflare/cloudflared:latest
        command: tunnel run
        network_mode: host
        restart: always
        environment:
            - TUNNEL_TOKEN=